export const USER_DATA_CHANGE = "USER_DATA_CHANGE";
export const LOADER_ON = "LOADER_ON";
export const LOADER_OFF = "LOADER_OFF";
export const USER_SET_AVATAR = "USER_SET_AVATAR";
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
